apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-service
  labels:
    app: zepto-storefront
spec:
  type: NodePort
  selector:
    app: zepto-storefront
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
